---
title: tblocks tutorial
author: Detlef Groth, University of Potsdam
date: 2026-06-20 07:54
---

## Introduction

_tblocks_ is a Tcl application and Tcl package which can be used to translate
simple Markdown files into SVG graphics.

Here the typical Hello World example with Markdown code 
which be automatically converted to a SVG graphics using a command line like
`tblocks hello.md hello.svg`: 

```{.shell label=hello1 cmd="tclsh ../tblocks/tblocks.tcl %i %b.svg" chunk.ext=md ext=svg fig.width=600}
## Hello

- entry 1
- entry 2
- entry 3

There can be as well some more text
in the lines below of the list.

## World!

- entry 4
- entry 5
- entry 6

There can be as well some more text
in the lines below of the list.
```

You can see the default color coding and the default diagram style which is
blocks. By using a YAML header you can changing these defaults.

## Styling the Diagram

There are two ways to change the diagram type, the font and the colors for the
output. Either you provide the application the appropriate command line
option, or you give these settings within a YAML header section at the
beginning of the Markdown file.

### Styling Colors

Here is a modified version where we set the colors for the first diagram to magentish:

```{.shell label=hello2 cmd="tclsh ../tblocks/tblocks.tcl %i %b.svg" chunk.ext=md ext=svg fig.width=600}
---
color1: "#DDDDFF" "#BBBBEE" "#404090"
---
## Hello

- entry 1
- entry 2
- entry 3

There can be as well some more text
in the lines below of the list.

## World!

- entry 4
- entry 5
- entry 6

There can be as well some more text
in the lines below of the list.
```

The default colors are based on the standard order of ANSI colors, so we have
black, which is used for the text, then pastel version of red, green, yellow,
blue, magenta and cyan. Here you see an extension of the first plot. For space issues I hide most of the Markdown code here:

```
## Hello Red

- entry 1
- entry 2
- entry 3

There can be as well some more text
in the lines below of the list.

## Hello Green

- entry 4
...
```



```{.shell label=hello3 cmd="tclsh ../tblocks/tblocks.tcl %i %b.svg" chunk.ext=md ext=svg fig.width=900 echo=FALSE}
## Hello Red

- entry 1
- entry 2
- entry 3

There can be as well some more text
in the lines below of the list.

## Hello Green

- entry 4
- entry 5
- entry 6

There can be as well some more text
in the lines below of the list.

## Hello Yellow

- entry 7
- entry 8
- entry 9

There can be as well some more text
in the lines below of the list.

## Hello BLue

- entry 10
- entry 11
- entry 12

There can be as well some more text
in the lines below of the list.

## Hello Magenta

- entry 13
- entry 14
- entry 15

There can be as well some more text
in the lines below of the list.

## Hello Cyan

- entry 16
- entry 17
- entry 18

There can be as well some more text
in the lines below of the list.
```


